services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  wagtail:
    build: .
    container_name: wagtail_container
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: "./"
        target: "/app"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db

volumes:
  postgres_data:
